[build]
base = "portfolio"
command = "npm run build"
publish = "dist"

[context]
[context.production]
command = "npm install && npm run build"

[context.develop]
command = "npm install && npm start"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200